- name: Remove old docker packages
  become: true
  apt:
    name: '{{ item }}'
    state: absent
  loop:
    - 'docker'
    - 'docker-engine'
    - 'docker.io'
    - 'containerd'
    - 'runc'
- name: Install required packages
  become: true
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'gnupg-agent'
    - 'software-properties-common'
- name: Add docker gpg apt key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add docker repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present
- name: Install docker packages
  become: true
  apt: 
    name: "{{ item }}"
    state: latest
  loop: 
    - 'docker-ce'
    - 'docker-ce-cli'
    - 'containerd.io'
- name: Add docker group
  become: true
  group:
    name: docker
    state: present
- name: Add vagrant user to docker group
  become: true
  user:
    name: vagrant
    groups: 
      - docker