- name: Update and upgrade all apt packages
  become: true
  apt:
    upgrade: dist
    update_cache: yes
- name: Install apt packages
  become: true
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - 'python3'
    - 'python3-pip'
    - 'python-docker'
- name: Include docker install tasks
  include: docker.yml
- name: Include setup network tasks
  include: network.yml