- name: Change interface mask
  become: true
  lineinfile:
    path: /etc/network/interfaces
    regexp: '^      netmask 255\.255\.255\.0$'
    line: '      netmask 255.255.0.0'
- name: Setup default gateway
  become: true
  lineinfile:
    path: /etc/network/interfaces
    insertbefore: '^      netmask 255\.255\.0\.0$'
    line: '      gateway 192.168.0.1'
- name: Reset interface
  become: true
  ignore_errors: yes
  command: '{{ item }}'
  loop:
    - 'ifdown eth1'
    - 'ifup eth1'