- name: Include kubectl install tasks
  include: kubectl.yml
- name: Include helm install tasks
  include: helm.yml
- name: Include rke install tasks
  include: rke.yml
- name: Include create cluster tasks
  include: rke_cluster.yml